version: '3'

services:
  notebook:
    image: breakerlab/dimpl:v1.0.2
    ports:
      - 127.0.0.1::8888
    environment:
      - GRANT_SUDO=yes
    volumes:
      - ./:/home/jovyan/work
    restart: always
    container_name: ${DIMPL_CONTAINER}
    entrypoint: [tini, --]
    env_file: .env
    command: [start-notebook.sh, --allow-root, --no-browser]
